[package]
name = "capture"
version = "0.1.0"
edition = "2024"

[dependencies]
collector_core = { path = "../core", package = "core" }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.56", features = [
  "Foundation",
  "Graphics_Capture",
  "Graphics_DirectX",
  "Graphics_DirectX_Direct3D11",
  "Win32_Foundation",
  "Win32_Graphics_Direct3D",
  "Win32_Graphics_Direct3D11",
  "Win32_Graphics_Dxgi",
  "Win32_System_WinRT",
  "Win32_UI_WindowsAndMessaging",
] }
