[package]
name = "gui"
version = "0.1.0"
edition = "2024"

[dependencies]
app = { path = "../app" }
capture = { path = "../capture" }
collector_core = { path = "../core", package = "core" }
input = { path = "../input" }
zip = "0.6"
